name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show workspace
        run: |
          pwd
          ls -la
          echo "Branch: $GITHUB_REF"
          python3 --version || true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Ensure src/ is on PYTHONPATH so imports like `from iris_app...` work
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE/src" >> $GITHUB_ENV

      - name: Debug environment
        run: |
          echo "PYTHONPATH=$PYTHONPATH"
          python -c "import sys; print('sys.path='); print('\n'.join(sys.path))"
          pip list

      - name: Collect tests
        run: pytest --collect-only -q

      - name: Run tests
        run: pytest -vv --maxfail=1

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: vderosen/streamlit-iris-dsbproject, vderosen/streamlit-iris-dsbproject:${{ github.ref_name }}
            